#doesn't work
version: '3.7'

services:
  app:
    image: 'wikime_storage:latest'
    build:
      context: .
    expose:
      - 8081
    restart: on-failure
    depends_on:
      - mongo

  mongo:
    image: 'mongo:4.4.3'
    container_name: wikime-storage
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./datadir:/var/lib/mongo